version: '3.1'
services:
  users:
    image: mongo
    restart: always
    ports:
      - "8002:27017"
    volumes:
      - ./data:/users
  skills:
    image: mongo
    restart: always
    ports:
      - "8001:27017"
    volumes:
      - ./data:/data/skills
  gateway_logging:
    image: mongo
    restart: always
    ports:
      - "8003:27017"
    volumes:
      - ./data:/logging
  skills_logging:
    image: mongo
    restart: always
    ports:
      - "8004:27017"
    volumes:
      - ./data:/skills_logging
  users_seeds:
    build:
      context: $PWD
      dockerfile: Dockerfile.users
  skills_seeds:
    build:
      context: $PWD
      dockerfile: Dockerfile.skills
