swagger: '2.0'
info:
  version: v1
  title: Skills API MicroService
  description: >-
    This is the Skills API to pull skills from data service and to be used by
    NodeJS API Gateway.
  contact:
    email: evgeniy.poznyak@gmail.com
paths:
  /Skills:
    get:
      tags:
        - Skills
      operationId: Find
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SkillListDto'
    post:
      tags:
        - Skills
      operationId: Save
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: content
          in: body
          required: false
          schema:
            $ref: '#/definitions/SkillDto'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SkillDto'
definitions:
  SkillListDto:
    type: object
    properties:
      skills:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/SkillDto'
  SkillDto:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      panel:
        type: string
      version:
        type: string
      logo:
        type: string
      order:
        type: string
      description:
        type: string
      projects:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/ProjectDto'
  ProjectDto:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      companyName:
        type: string
      website:
        type: string
      github:
        type: string
      logo:
        type: string
      dateCreated:
        type: string
      cardCover:
        type: string
      images:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/ProjectImagesDto'
      shortDescription:
        type: string
      longDescription:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/LongDescriptionDto'
  ProjectImagesDto:
    type: object
    properties:
      label:
        type: string
      path:
        type: string
  LongDescriptionDto:
    type: object
    properties:
      picture:
        type: string
      description:
        type: string